/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as BillingCheckoutRouteImport } from './routes/billing/checkout'
import { Route as BillingPlansRouteImport } from './routes/billing/plans'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as WorkspacesSlugRouteImport } from './routes/workspaces/$slug'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BillingRoute,
} as any)
const BillingPlansRoute = BillingPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => BillingRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesSlugRoute = WorkspacesSlugRouteImport.update({
  id: '/workspaces/$slug',
  path: '/workspaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/revenue': typeof RevenueRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/plans': typeof BillingPlansRoute
  '/billing/success': typeof BillingSuccessRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/team': typeof SettingsTeamRoute
  '/workspaces/$slug': typeof WorkspacesSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/revenue': typeof RevenueRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/plans': typeof BillingPlansRoute
  '/billing/success': typeof BillingSuccessRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/team': typeof SettingsTeamRoute
  '/workspaces/$slug': typeof WorkspacesSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/billing': typeof BillingRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/revenue': typeof RevenueRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/plans': typeof BillingPlansRoute
  '/billing/success': typeof BillingSuccessRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/team': typeof SettingsTeamRoute
  '/workspaces/$slug': typeof WorkspacesSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/billing'
    | '/integrations'
    | '/onboarding'
    | '/overview'
    | '/revenue'
    | '/support'
    | '/team'
    | '/usage'
    | '/billing/checkout'
    | '/billing/plans'
    | '/billing/success'
    | '/join/$token'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/workspaces/$slug'
    | '/workspaces/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/billing'
    | '/integrations'
    | '/onboarding'
    | '/overview'
    | '/revenue'
    | '/support'
    | '/team'
    | '/usage'
    | '/billing/checkout'
    | '/billing/plans'
    | '/billing/success'
    | '/join/$token'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/workspaces/$slug'
    | '/workspaces/new'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/billing'
    | '/integrations'
    | '/onboarding'
    | '/overview'
    | '/revenue'
    | '/support'
    | '/team'
    | '/usage'
    | '/billing/checkout'
    | '/billing/plans'
    | '/billing/success'
    | '/join/$token'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/team'
    | '/workspaces/$slug'
    | '/workspaces/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BillingRoute: typeof BillingRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
  RevenueRoute: typeof RevenueRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  UsageRoute: typeof UsageRoute
  JoinTokenRoute: typeof JoinTokenRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  WorkspacesSlugRoute: typeof WorkspacesSlugRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/plans': {
      id: '/billing/plans'
      path: '/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof BillingPlansRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof BillingRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$slug': {
      id: '/workspaces/$slug'
      path: '/workspaces/$slug'
      fullPath: '/workspaces/$slug'
      preLoaderRoute: typeof WorkspacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BillingRouteChildren {
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  BillingPlansRoute: typeof BillingPlansRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingPlansRoute: BillingPlansRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  BillingRoute: BillingRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
  RevenueRoute: RevenueRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  UsageRoute: UsageRoute,
  JoinTokenRoute: JoinTokenRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  WorkspacesSlugRoute: WorkspacesSlugRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
