/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BusinessIndexRouteImport } from './routes/business/index'
import { Route as BusinessTypeRouteImport } from './routes/business/$type'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSectionRouteImport } from './routes/docs/$section'
import { Route as ErrorsCodeRouteImport } from './routes/errors.$code'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsMarketplaceRouteImport } from './routes/products/marketplace'
import { Route as ProductsWorkspacesRouteImport } from './routes/products/workspaces'
import { Route as ProductsModulesIndexRouteImport } from './routes/products/modules/index'
import { Route as ProductsModulesModuleRouteImport } from './routes/products/modules/$module'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/business/',
  path: '/business/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessTypeRoute = BusinessTypeRouteImport.update({
  id: '/business/$type',
  path: '/business/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSectionRoute = DocsSectionRouteImport.update({
  id: '/docs/$section',
  path: '/docs/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsCodeRoute = ErrorsCodeRouteImport.update({
  id: '/errors/$code',
  path: '/errors/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMarketplaceRoute = ProductsMarketplaceRouteImport.update({
  id: '/products/marketplace',
  path: '/products/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWorkspacesRoute = ProductsWorkspacesRouteImport.update({
  id: '/products/workspaces',
  path: '/products/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsModulesIndexRoute = ProductsModulesIndexRouteImport.update({
  id: '/products/modules/',
  path: '/products/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsModulesModuleRoute = ProductsModulesModuleRouteImport.update({
  id: '/products/modules/$module',
  path: '/products/modules/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/business/$type': typeof BusinessTypeRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/$section': typeof DocsSectionRoute
  '/errors/$code': typeof ErrorsCodeRoute
  '/products/marketplace': typeof ProductsMarketplaceRoute
  '/products/workspaces': typeof ProductsWorkspacesRoute
  '/business/': typeof BusinessIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/modules/$module': typeof ProductsModulesModuleRoute
  '/products/modules/': typeof ProductsModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/business/$type': typeof BusinessTypeRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/$section': typeof DocsSectionRoute
  '/errors/$code': typeof ErrorsCodeRoute
  '/products/marketplace': typeof ProductsMarketplaceRoute
  '/products/workspaces': typeof ProductsWorkspacesRoute
  '/business': typeof BusinessIndexRoute
  '/docs': typeof DocsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/products/modules/$module': typeof ProductsModulesModuleRoute
  '/products/modules': typeof ProductsModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brand': typeof BrandRoute
  '/changelog': typeof ChangelogRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/security': typeof SecurityRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/business/$type': typeof BusinessTypeRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/docs/$section': typeof DocsSectionRoute
  '/errors/$code': typeof ErrorsCodeRoute
  '/products/marketplace': typeof ProductsMarketplaceRoute
  '/products/workspaces': typeof ProductsWorkspacesRoute
  '/business/': typeof BusinessIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/products/modules/$module': typeof ProductsModulesModuleRoute
  '/products/modules/': typeof ProductsModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/brand'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/security'
    | '/support'
    | '/terms'
    | '/business/$type'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/docs/$section'
    | '/errors/$code'
    | '/products/marketplace'
    | '/products/workspaces'
    | '/business/'
    | '/docs/'
    | '/products/'
    | '/products/modules/$module'
    | '/products/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/brand'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/security'
    | '/support'
    | '/terms'
    | '/business/$type'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/docs/$section'
    | '/errors/$code'
    | '/products/marketplace'
    | '/products/workspaces'
    | '/business'
    | '/docs'
    | '/products'
    | '/products/modules/$module'
    | '/products/modules'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/brand'
    | '/changelog'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/security'
    | '/support'
    | '/terms'
    | '/business/$type'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/docs/$section'
    | '/errors/$code'
    | '/products/marketplace'
    | '/products/workspaces'
    | '/business/'
    | '/docs/'
    | '/products/'
    | '/products/modules/$module'
    | '/products/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandRoute: typeof BrandRoute
  ChangelogRoute: typeof ChangelogRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SecurityRoute: typeof SecurityRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  BusinessTypeRoute: typeof BusinessTypeRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  DocsSectionRoute: typeof DocsSectionRoute
  ErrorsCodeRoute: typeof ErrorsCodeRoute
  ProductsMarketplaceRoute: typeof ProductsMarketplaceRoute
  ProductsWorkspacesRoute: typeof ProductsWorkspacesRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsModulesModuleRoute: typeof ProductsModulesModuleRoute
  ProductsModulesIndexRoute: typeof ProductsModulesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/business'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$type': {
      id: '/business/$type'
      path: '/business/$type'
      fullPath: '/business/$type'
      preLoaderRoute: typeof BusinessTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$section': {
      id: '/docs/$section'
      path: '/docs/$section'
      fullPath: '/docs/$section'
      preLoaderRoute: typeof DocsSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/$code': {
      id: '/errors/$code'
      path: '/errors/$code'
      fullPath: '/errors/$code'
      preLoaderRoute: typeof ErrorsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/marketplace': {
      id: '/products/marketplace'
      path: '/products/marketplace'
      fullPath: '/products/marketplace'
      preLoaderRoute: typeof ProductsMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/workspaces': {
      id: '/products/workspaces'
      path: '/products/workspaces'
      fullPath: '/products/workspaces'
      preLoaderRoute: typeof ProductsWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/modules/': {
      id: '/products/modules/'
      path: '/products/modules'
      fullPath: '/products/modules/'
      preLoaderRoute: typeof ProductsModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/modules/$module': {
      id: '/products/modules/$module'
      path: '/products/modules/$module'
      fullPath: '/products/modules/$module'
      preLoaderRoute: typeof ProductsModulesModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandRoute: BrandRoute,
  ChangelogRoute: ChangelogRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SecurityRoute: SecurityRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  BusinessTypeRoute: BusinessTypeRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  DocsSectionRoute: DocsSectionRoute,
  ErrorsCodeRoute: ErrorsCodeRoute,
  ProductsMarketplaceRoute: ProductsMarketplaceRoute,
  ProductsWorkspacesRoute: ProductsWorkspacesRoute,
  BusinessIndexRoute: BusinessIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsModulesModuleRoute: ProductsModulesModuleRoute,
  ProductsModulesIndexRoute: ProductsModulesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
