/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugHandoffRouteImport } from './routes/$slug.handoff'
import { Route as SlugVerifyRouteImport } from './routes/$slug.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugHandoffRoute = SlugHandoffRouteImport.update({
  id: '/$slug/handoff',
  path: '/$slug/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugVerifyRoute = SlugVerifyRouteImport.update({
  id: '/$slug/verify',
  path: '/$slug/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug/handoff': typeof SlugHandoffRoute
  '/$slug/verify': typeof SlugVerifyRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/handoff': typeof SlugHandoffRoute
  '/$slug/verify': typeof SlugVerifyRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug/handoff': typeof SlugHandoffRoute
  '/$slug/verify': typeof SlugVerifyRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug/handoff' | '/$slug/verify' | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug/handoff' | '/$slug/verify' | '/$slug'
  id: '__root__' | '/' | '/$slug/handoff' | '/$slug/verify' | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugHandoffRoute: typeof SlugHandoffRoute
  SlugVerifyRoute: typeof SlugVerifyRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/handoff': {
      id: '/$slug/handoff'
      path: '/$slug/handoff'
      fullPath: '/$slug/handoff'
      preLoaderRoute: typeof SlugHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/verify': {
      id: '/$slug/verify'
      path: '/$slug/verify'
      fullPath: '/$slug/verify'
      preLoaderRoute: typeof SlugVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugHandoffRoute: SlugHandoffRoute,
  SlugVerifyRoute: SlugVerifyRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
