/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/$workspace'
import { Route as NativeSigninRouteImport } from './routes/native-signin'
import { Route as WorkspaceIndexRouteImport } from './routes/$workspace.index'
import { Route as WorkspaceSplatRouteImport } from './routes/$workspace.$'
import { Route as WorkspaceModuleRouteImport } from './routes/$workspace.$module'
import { Route as WorkspaceAuditRouteImport } from './routes/$workspace.audit'
import { Route as WorkspaceConnectRouteImport } from './routes/$workspace.connect'
import { Route as WorkspaceMediaRouteImport } from './routes/$workspace.media'
import { Route as WorkspaceSettingsRouteImport } from './routes/$workspace.settings'
import { Route as WorkspaceStatesRouteImport } from './routes/$workspace.states'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as WorkspaceModuleIndexRouteImport } from './routes/$workspace.$module.index'
import { Route as WorkspaceModuleSectionRouteImport } from './routes/$workspace.$module.$section'
import { Route as WorkspaceErrorsIndexRouteImport } from './routes/$workspace.errors.index'
import { Route as WorkspaceErrorsCodeRouteImport } from './routes/$workspace.errors.$code'
import { Route as WorkspaceSettingsIndexRouteImport } from './routes/$workspace.settings.index'
import { Route as WorkspaceSettingsSectionRouteImport } from './routes/$workspace.settings.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeSigninRoute = NativeSigninRouteImport.update({
  id: '/native-signin',
  path: '/native-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSplatRoute = WorkspaceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceModuleRoute = WorkspaceModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAuditRoute = WorkspaceAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceConnectRoute = WorkspaceConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceMediaRoute = WorkspaceMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceStatesRoute = WorkspaceStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceModuleIndexRoute = WorkspaceModuleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceModuleRoute,
} as any)
const WorkspaceModuleSectionRoute = WorkspaceModuleSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => WorkspaceModuleRoute,
} as any)
const WorkspaceErrorsIndexRoute = WorkspaceErrorsIndexRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceErrorsCodeRoute = WorkspaceErrorsCodeRouteImport.update({
  id: '/errors/$code',
  path: '/errors/$code',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsIndexRoute = WorkspaceSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSettingsRoute,
} as any)
const WorkspaceSettingsSectionRoute =
  WorkspaceSettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => WorkspaceSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/native-signin': typeof NativeSigninRoute
  '/$workspace/$': typeof WorkspaceSplatRoute
  '/$workspace/$module': typeof WorkspaceModuleRouteWithChildren
  '/$workspace/audit': typeof WorkspaceAuditRoute
  '/$workspace/connect': typeof WorkspaceConnectRoute
  '/$workspace/media': typeof WorkspaceMediaRoute
  '/$workspace/settings': typeof WorkspaceSettingsRouteWithChildren
  '/$workspace/states': typeof WorkspaceStatesRoute
  '/sign/$token': typeof SignTokenRoute
  '/$workspace/': typeof WorkspaceIndexRoute
  '/$workspace/$module/$section': typeof WorkspaceModuleSectionRoute
  '/$workspace/errors/$code': typeof WorkspaceErrorsCodeRoute
  '/$workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/$workspace/$module/': typeof WorkspaceModuleIndexRoute
  '/$workspace/errors/': typeof WorkspaceErrorsIndexRoute
  '/$workspace/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/native-signin': typeof NativeSigninRoute
  '/$workspace/$': typeof WorkspaceSplatRoute
  '/$workspace/audit': typeof WorkspaceAuditRoute
  '/$workspace/connect': typeof WorkspaceConnectRoute
  '/$workspace/media': typeof WorkspaceMediaRoute
  '/$workspace/states': typeof WorkspaceStatesRoute
  '/sign/$token': typeof SignTokenRoute
  '/$workspace': typeof WorkspaceIndexRoute
  '/$workspace/$module/$section': typeof WorkspaceModuleSectionRoute
  '/$workspace/errors/$code': typeof WorkspaceErrorsCodeRoute
  '/$workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/$workspace/$module': typeof WorkspaceModuleIndexRoute
  '/$workspace/errors': typeof WorkspaceErrorsIndexRoute
  '/$workspace/settings': typeof WorkspaceSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/native-signin': typeof NativeSigninRoute
  '/$workspace/$': typeof WorkspaceSplatRoute
  '/$workspace/$module': typeof WorkspaceModuleRouteWithChildren
  '/$workspace/audit': typeof WorkspaceAuditRoute
  '/$workspace/connect': typeof WorkspaceConnectRoute
  '/$workspace/media': typeof WorkspaceMediaRoute
  '/$workspace/settings': typeof WorkspaceSettingsRouteWithChildren
  '/$workspace/states': typeof WorkspaceStatesRoute
  '/sign/$token': typeof SignTokenRoute
  '/$workspace/': typeof WorkspaceIndexRoute
  '/$workspace/$module/$section': typeof WorkspaceModuleSectionRoute
  '/$workspace/errors/$code': typeof WorkspaceErrorsCodeRoute
  '/$workspace/settings/$section': typeof WorkspaceSettingsSectionRoute
  '/$workspace/$module/': typeof WorkspaceModuleIndexRoute
  '/$workspace/errors/': typeof WorkspaceErrorsIndexRoute
  '/$workspace/settings/': typeof WorkspaceSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | '/native-signin'
    | '/$workspace/$'
    | '/$workspace/$module'
    | '/$workspace/audit'
    | '/$workspace/connect'
    | '/$workspace/media'
    | '/$workspace/settings'
    | '/$workspace/states'
    | '/sign/$token'
    | '/$workspace/'
    | '/$workspace/$module/$section'
    | '/$workspace/errors/$code'
    | '/$workspace/settings/$section'
    | '/$workspace/$module/'
    | '/$workspace/errors/'
    | '/$workspace/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/native-signin'
    | '/$workspace/$'
    | '/$workspace/audit'
    | '/$workspace/connect'
    | '/$workspace/media'
    | '/$workspace/states'
    | '/sign/$token'
    | '/$workspace'
    | '/$workspace/$module/$section'
    | '/$workspace/errors/$code'
    | '/$workspace/settings/$section'
    | '/$workspace/$module'
    | '/$workspace/errors'
    | '/$workspace/settings'
  id:
    | '__root__'
    | '/'
    | '/$workspace'
    | '/native-signin'
    | '/$workspace/$'
    | '/$workspace/$module'
    | '/$workspace/audit'
    | '/$workspace/connect'
    | '/$workspace/media'
    | '/$workspace/settings'
    | '/$workspace/states'
    | '/sign/$token'
    | '/$workspace/'
    | '/$workspace/$module/$section'
    | '/$workspace/errors/$code'
    | '/$workspace/settings/$section'
    | '/$workspace/$module/'
    | '/$workspace/errors/'
    | '/$workspace/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  NativeSigninRoute: typeof NativeSigninRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace': {
      id: '/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-signin': {
      id: '/native-signin'
      path: '/native-signin'
      fullPath: '/native-signin'
      preLoaderRoute: typeof NativeSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/': {
      id: '/$workspace/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/$': {
      id: '/$workspace/$'
      path: '/$'
      fullPath: '/$workspace/$'
      preLoaderRoute: typeof WorkspaceSplatRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/$module': {
      id: '/$workspace/$module'
      path: '/$module'
      fullPath: '/$workspace/$module'
      preLoaderRoute: typeof WorkspaceModuleRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/audit': {
      id: '/$workspace/audit'
      path: '/audit'
      fullPath: '/$workspace/audit'
      preLoaderRoute: typeof WorkspaceAuditRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/connect': {
      id: '/$workspace/connect'
      path: '/connect'
      fullPath: '/$workspace/connect'
      preLoaderRoute: typeof WorkspaceConnectRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/media': {
      id: '/$workspace/media'
      path: '/media'
      fullPath: '/$workspace/media'
      preLoaderRoute: typeof WorkspaceMediaRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/settings': {
      id: '/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/states': {
      id: '/$workspace/states'
      path: '/states'
      fullPath: '/$workspace/states'
      preLoaderRoute: typeof WorkspaceStatesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/$module/': {
      id: '/$workspace/$module/'
      path: '/'
      fullPath: '/$workspace/$module/'
      preLoaderRoute: typeof WorkspaceModuleIndexRouteImport
      parentRoute: typeof WorkspaceModuleRoute
    }
    '/$workspace/$module/$section': {
      id: '/$workspace/$module/$section'
      path: '/$section'
      fullPath: '/$workspace/$module/$section'
      preLoaderRoute: typeof WorkspaceModuleSectionRouteImport
      parentRoute: typeof WorkspaceModuleRoute
    }
    '/$workspace/errors/': {
      id: '/$workspace/errors/'
      path: '/errors'
      fullPath: '/$workspace/errors/'
      preLoaderRoute: typeof WorkspaceErrorsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/errors/$code': {
      id: '/$workspace/errors/$code'
      path: '/errors/$code'
      fullPath: '/$workspace/errors/$code'
      preLoaderRoute: typeof WorkspaceErrorsCodeRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/settings/': {
      id: '/$workspace/settings/'
      path: '/'
      fullPath: '/$workspace/settings/'
      preLoaderRoute: typeof WorkspaceSettingsIndexRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
    '/$workspace/settings/$section': {
      id: '/$workspace/settings/$section'
      path: '/$section'
      fullPath: '/$workspace/settings/$section'
      preLoaderRoute: typeof WorkspaceSettingsSectionRouteImport
      parentRoute: typeof WorkspaceSettingsRoute
    }
  }
}

interface WorkspaceModuleRouteChildren {
  WorkspaceModuleSectionRoute: typeof WorkspaceModuleSectionRoute
  WorkspaceModuleIndexRoute: typeof WorkspaceModuleIndexRoute
}

const WorkspaceModuleRouteChildren: WorkspaceModuleRouteChildren = {
  WorkspaceModuleSectionRoute: WorkspaceModuleSectionRoute,
  WorkspaceModuleIndexRoute: WorkspaceModuleIndexRoute,
}

const WorkspaceModuleRouteWithChildren = WorkspaceModuleRoute._addFileChildren(
  WorkspaceModuleRouteChildren,
)

interface WorkspaceSettingsRouteChildren {
  WorkspaceSettingsSectionRoute: typeof WorkspaceSettingsSectionRoute
  WorkspaceSettingsIndexRoute: typeof WorkspaceSettingsIndexRoute
}

const WorkspaceSettingsRouteChildren: WorkspaceSettingsRouteChildren = {
  WorkspaceSettingsSectionRoute: WorkspaceSettingsSectionRoute,
  WorkspaceSettingsIndexRoute: WorkspaceSettingsIndexRoute,
}

const WorkspaceSettingsRouteWithChildren =
  WorkspaceSettingsRoute._addFileChildren(WorkspaceSettingsRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceSplatRoute: typeof WorkspaceSplatRoute
  WorkspaceModuleRoute: typeof WorkspaceModuleRouteWithChildren
  WorkspaceAuditRoute: typeof WorkspaceAuditRoute
  WorkspaceConnectRoute: typeof WorkspaceConnectRoute
  WorkspaceMediaRoute: typeof WorkspaceMediaRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRouteWithChildren
  WorkspaceStatesRoute: typeof WorkspaceStatesRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
  WorkspaceErrorsCodeRoute: typeof WorkspaceErrorsCodeRoute
  WorkspaceErrorsIndexRoute: typeof WorkspaceErrorsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceSplatRoute: WorkspaceSplatRoute,
  WorkspaceModuleRoute: WorkspaceModuleRouteWithChildren,
  WorkspaceAuditRoute: WorkspaceAuditRoute,
  WorkspaceConnectRoute: WorkspaceConnectRoute,
  WorkspaceMediaRoute: WorkspaceMediaRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRouteWithChildren,
  WorkspaceStatesRoute: WorkspaceStatesRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
  WorkspaceErrorsCodeRoute: WorkspaceErrorsCodeRoute,
  WorkspaceErrorsIndexRoute: WorkspaceErrorsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  NativeSigninRoute: NativeSigninRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
