/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/$workspace'
import { Route as NativeSigninRouteImport } from './routes/native-signin'
import { Route as WorkspaceIndexRouteImport } from './routes/$workspace.index'
import { Route as WorkspaceModuleRouteImport } from './routes/$workspace.$module'
import { Route as WorkspaceConnectRouteImport } from './routes/$workspace.connect'
import { Route as SignTokenRouteImport } from './routes/sign.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const NativeSigninRoute = NativeSigninRouteImport.update({
  id: '/native-signin',
  path: '/native-signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceModuleRoute = WorkspaceModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceConnectRoute = WorkspaceConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => WorkspaceRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/native-signin': typeof NativeSigninRoute
  '/$workspace/$module': typeof WorkspaceModuleRoute
  '/$workspace/connect': typeof WorkspaceConnectRoute
  '/sign/$token': typeof SignTokenRoute
  '/$workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/native-signin': typeof NativeSigninRoute
  '/$workspace/$module': typeof WorkspaceModuleRoute
  '/$workspace/connect': typeof WorkspaceConnectRoute
  '/sign/$token': typeof SignTokenRoute
  '/$workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/native-signin': typeof NativeSigninRoute
  '/$workspace/$module': typeof WorkspaceModuleRoute
  '/$workspace/connect': typeof WorkspaceConnectRoute
  '/sign/$token': typeof SignTokenRoute
  '/$workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | '/native-signin'
    | '/$workspace/$module'
    | '/$workspace/connect'
    | '/sign/$token'
    | '/$workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/native-signin'
    | '/$workspace/$module'
    | '/$workspace/connect'
    | '/sign/$token'
    | '/$workspace'
  id:
    | '__root__'
    | '/'
    | '/$workspace'
    | '/native-signin'
    | '/$workspace/$module'
    | '/$workspace/connect'
    | '/sign/$token'
    | '/$workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  NativeSigninRoute: typeof NativeSigninRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace': {
      id: '/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/native-signin': {
      id: '/native-signin'
      path: '/native-signin'
      fullPath: '/native-signin'
      preLoaderRoute: typeof NativeSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/': {
      id: '/$workspace/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/$module': {
      id: '/$workspace/$module'
      path: '/$module'
      fullPath: '/$workspace/$module'
      preLoaderRoute: typeof WorkspaceModuleRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/connect': {
      id: '/$workspace/connect'
      path: '/connect'
      fullPath: '/$workspace/connect'
      preLoaderRoute: typeof WorkspaceConnectRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceModuleRoute: typeof WorkspaceModuleRoute
  WorkspaceConnectRoute: typeof WorkspaceConnectRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceModuleRoute: WorkspaceModuleRoute,
  WorkspaceConnectRoute: WorkspaceConnectRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  NativeSigninRoute: NativeSigninRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
