/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnboardingPreviewRouteImport } from './routes/onboarding-preview'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ActivityNotificationsRouteImport } from './routes/activity/notifications'
import { Route as BillingCheckoutRouteImport } from './routes/billing/checkout'
import { Route as BillingCreditsRouteImport } from './routes/billing/credits'
import { Route as BillingSuccessRouteImport } from './routes/billing/success'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as OrganizationsNewRouteImport } from './routes/organizations/new'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsSessionsRouteImport } from './routes/settings/sessions'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as TeamInvitationsRouteImport } from './routes/team/invitations'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces/index'
import { Route as WorkspacesSlugRouteImport } from './routes/workspaces/$slug'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPreviewRoute = OnboardingPreviewRouteImport.update({
  id: '/onboarding-preview',
  path: '/onboarding-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityNotificationsRoute = ActivityNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ActivityRoute,
} as any)
const BillingCheckoutRoute = BillingCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BillingRoute,
} as any)
const BillingCreditsRoute = BillingCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => BillingRoute,
} as any)
const BillingSuccessRoute = BillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BillingRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamInvitationsRoute = TeamInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => TeamRoute,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesSlugRoute = WorkspacesSlugRouteImport.update({
  id: '/workspaces/$slug',
  path: '/workspaces/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/billing': typeof BillingRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRouteWithChildren
  '/usage': typeof UsageRoute
  '/activity/notifications': typeof ActivityNotificationsRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/credits': typeof BillingCreditsRoute
  '/billing/success': typeof BillingSuccessRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/team/invitations': typeof TeamInvitationsRoute
  '/workspaces/$slug': typeof WorkspacesSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/billing': typeof BillingRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRouteWithChildren
  '/usage': typeof UsageRoute
  '/activity/notifications': typeof ActivityNotificationsRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/credits': typeof BillingCreditsRoute
  '/billing/success': typeof BillingSuccessRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/team/invitations': typeof TeamInvitationsRoute
  '/workspaces/$slug': typeof WorkspacesSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces': typeof WorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRouteWithChildren
  '/billing': typeof BillingRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-preview': typeof OnboardingPreviewRoute
  '/roles': typeof RolesRoute
  '/support': typeof SupportRoute
  '/team': typeof TeamRouteWithChildren
  '/usage': typeof UsageRoute
  '/activity/notifications': typeof ActivityNotificationsRoute
  '/billing/checkout': typeof BillingCheckoutRoute
  '/billing/credits': typeof BillingCreditsRoute
  '/billing/success': typeof BillingSuccessRoute
  '/join/$token': typeof JoinTokenRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/team/invitations': typeof TeamInvitationsRoute
  '/workspaces/$slug': typeof WorkspacesSlugRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/workspaces/': typeof WorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/billing'
    | '/integrations'
    | '/onboarding'
    | '/onboarding-preview'
    | '/roles'
    | '/support'
    | '/team'
    | '/usage'
    | '/activity/notifications'
    | '/billing/checkout'
    | '/billing/credits'
    | '/billing/success'
    | '/join/$token'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/team'
    | '/team/invitations'
    | '/workspaces/$slug'
    | '/workspaces/new'
    | '/workspaces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/billing'
    | '/integrations'
    | '/onboarding'
    | '/onboarding-preview'
    | '/roles'
    | '/support'
    | '/team'
    | '/usage'
    | '/activity/notifications'
    | '/billing/checkout'
    | '/billing/credits'
    | '/billing/success'
    | '/join/$token'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/team'
    | '/team/invitations'
    | '/workspaces/$slug'
    | '/workspaces/new'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/billing'
    | '/integrations'
    | '/onboarding'
    | '/onboarding-preview'
    | '/roles'
    | '/support'
    | '/team'
    | '/usage'
    | '/activity/notifications'
    | '/billing/checkout'
    | '/billing/credits'
    | '/billing/success'
    | '/join/$token'
    | '/organizations/new'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/sessions'
    | '/settings/team'
    | '/team/invitations'
    | '/workspaces/$slug'
    | '/workspaces/new'
    | '/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRouteWithChildren
  BillingRoute: typeof BillingRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingPreviewRoute: typeof OnboardingPreviewRoute
  RolesRoute: typeof RolesRoute
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRouteWithChildren
  UsageRoute: typeof UsageRoute
  JoinTokenRoute: typeof JoinTokenRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  WorkspacesSlugRoute: typeof WorkspacesSlugRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-preview': {
      id: '/onboarding-preview'
      path: '/onboarding-preview'
      fullPath: '/onboarding-preview'
      preLoaderRoute: typeof OnboardingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/notifications': {
      id: '/activity/notifications'
      path: '/notifications'
      fullPath: '/activity/notifications'
      preLoaderRoute: typeof ActivityNotificationsRouteImport
      parentRoute: typeof ActivityRoute
    }
    '/billing/checkout': {
      id: '/billing/checkout'
      path: '/checkout'
      fullPath: '/billing/checkout'
      preLoaderRoute: typeof BillingCheckoutRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/credits': {
      id: '/billing/credits'
      path: '/credits'
      fullPath: '/billing/credits'
      preLoaderRoute: typeof BillingCreditsRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/success': {
      id: '/billing/success'
      path: '/success'
      fullPath: '/billing/success'
      preLoaderRoute: typeof BillingSuccessRouteImport
      parentRoute: typeof BillingRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/invitations': {
      id: '/team/invitations'
      path: '/invitations'
      fullPath: '/team/invitations'
      preLoaderRoute: typeof TeamInvitationsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$slug': {
      id: '/workspaces/$slug'
      path: '/workspaces/$slug'
      fullPath: '/workspaces/$slug'
      preLoaderRoute: typeof WorkspacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ActivityRouteChildren {
  ActivityNotificationsRoute: typeof ActivityNotificationsRoute
}

const ActivityRouteChildren: ActivityRouteChildren = {
  ActivityNotificationsRoute: ActivityNotificationsRoute,
}

const ActivityRouteWithChildren = ActivityRoute._addFileChildren(
  ActivityRouteChildren,
)

interface BillingRouteChildren {
  BillingCheckoutRoute: typeof BillingCheckoutRoute
  BillingCreditsRoute: typeof BillingCreditsRoute
  BillingSuccessRoute: typeof BillingSuccessRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingCheckoutRoute: BillingCheckoutRoute,
  BillingCreditsRoute: BillingCreditsRoute,
  BillingSuccessRoute: BillingSuccessRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface TeamRouteChildren {
  TeamInvitationsRoute: typeof TeamInvitationsRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamInvitationsRoute: TeamInvitationsRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRouteWithChildren,
  BillingRoute: BillingRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingPreviewRoute: OnboardingPreviewRoute,
  RolesRoute: RolesRoute,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRouteWithChildren,
  UsageRoute: UsageRoute,
  JoinTokenRoute: JoinTokenRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  WorkspacesSlugRoute: WorkspacesSlugRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspacesIndexRoute: WorkspacesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
